"""add event_timestamp to events

Revision ID: 68827ca895b0
Revises: 8f1ba25dffea
Create Date: 2026-09-05 13:39:07.520791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68827ca895b0'
down_revision: Union[str, None] = '8f1ba25dffea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default evita quebrar se a tabela ja tiver linhas quando essa
    # migration rodar em outro ambiente (mesmo caso do posts.comments_count).
    op.add_column(
        'events',
        sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.alter_column('events', 'event_timestamp', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_timestamp')
    # ### end Alembic commands ###
