"""add comments_count to posts

Revision ID: 8f1ba25dffea
Revises: 00012952c48e
Create Date: 2026-09-05 13:20:57.591775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1ba25dffea'
down_revision: Union[str, None] = '00012952c48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default garante que linhas existentes recebam 0 em vez de
    # violar o NOT NULL (autogenerate não adiciona isso sozinho).
    op.add_column(
        'posts',
        sa.Column('comments_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('posts', 'comments_count', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comments_count')
    # ### end Alembic commands ###
